### ISSUE TITLE
データベース構造図の作成

### ISSUE THREAD

**Issue by veryfreshsato** [iwakura09la/class#1]

**Comment by ichiyasa-k** [comment]
完成しました
![スクリーンショット (3)](https://user-images.githubusercontent.com/104047917/173726439-cfc228e9-83c0-4cf4-98a3-77529ba7750d.png)

**Comment by ichiyasa-k** [comment]
実技はYesno型から数値型で1と0で表現することになりました

**Comment by ichiyasa-k** [comment]
エクセル
[Book1.xlsx](https://github.com/iwakura09la/class/files/8924102/Book1.xlsx)
